services:
  - type: web
    name: virtual-wall-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_BACKEND_URL
        sync: false
      - key: VITE_FRONTEND_URL
        sync: false 